# Generated by Django 5.0.3 on 2024-04-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_vendedor", models.CharField(max_length=100)),
                ("nome_loja", models.CharField(max_length=100)),
                ("nome_produto", models.CharField(max_length=200)),
                (
                    "quantidade_coletada",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("lote", models.CharField(max_length=50)),
                ("data_fabricacao", models.DateField()),
                ("motivo_da_coleta", models.TextField()),
                ("data_da_coleta", models.DateField()),
            ],
        ),
    ]
