# Generated by Django 5.0.3 on 2024-04-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="troca_confirmada",
            field=models.BooleanField(default=False),
        ),
    ]
