# Generated by Django 5.0.3 on 2024-04-10 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_products_troca_confirmada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="quantidade_coletada",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(10)]
            ),
        ),
    ]
